version: '3.7'

services:
  regression:
    image: cypress/included:latest
    working_dir: /usr/workspace
    volumes:
      - ./:/usr/workspace
    entrypoint: ["sh", "-c", "npm ci && npm run cy:createTender"]
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_PHONE_NUMBER=${ADMIN_PHONE_NUMBER}
      - VALID_PHONE_NUMBER=${VALID_PHONE_NUMBER}
      - BASE_URL=${BASE_URL}
      - STAGE_BASE_URL=${STAGE_BASE_URL}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
      - USER_PHONE_NUMBER=${USER_PHONE_NUMBER}
  
  allure:
    volumes:
      - ./:/usr/workspace
    entrypoint: ["sh", "-c", "allure generate allure-results --clean -o allure-report"]