
services:
  regression:
    image: cypress/included:latest
    working_dir: /usr/workspace
    volumes:
      - ./:/usr/workspace
    entrypoint: ["/bin/sh", "-c", "npm ci && npm run cy:createTender"]
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_PHONE_NUMBER=${ADMIN_PHONE_NUMBER}
      - VALID_PHONE_NUMBER=${VALID_PHONE_NUMBER}
      - BASE_URL=${BASE_URL}
      - STAGE_BASE_URL=${STAGE_BASE_URL}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
      - USER_PHONE_NUMBER=${USER_PHONE_NUMBER}

  allure:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/workspace
    command: ["/bin/sh", "-c", "allure generate --single-file allure-results --clean -o allure-report"]
    volumes: 
      - ./:/usr/workspace
 