name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Ui-tests via docker-compose
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_PHONE_NUMBER: ${{ secrets.ADMIN_PHONE_NUMBER }}
          VALID_PHONE_NUMBER: ${{ secrets.VALID_PHONE_NUMBER }}
          BASE_URL: ${{ secrets.BASE_URL }}
          STAGE_BASE_URL: ${{ secrets.STAGE_BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_PHONE_NUMBER: ${{ secrets.USER_PHONE_NUMBER }}
        run: |
          docker compose up --exit-code-from regression || true

      - name: Generate Allure report
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          docker compose run regression /bin/sh -c "allure generate  allure-results --clean -o allure-report"

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          